Repository hmcts/pip-shared-infrastructures, pull requests merged in 2024-08, with the labels that each got.

#177 PUB-2497- Downgraded staging non-prod environment from Premium to Basic
  stg.tfvars
  tf-redis-v6-main.tf
Labels: stg/destroy, prod/add-or-update

#179 PUB-1566 Add Crime Idam Credentials
  tf-kv-secrets-bootstrap.tf
Labels: stg/add-or-update, prod/add-or-update

#180 PUB-2511: Updating dependencies
  .terraform-version
  providers.tf
Labels: stg/add-or-update, prod/add-or-update

#181 PUB-2340 - Add new session key secret
  tf-kv-secrets.tf
Labels: stg/add-or-update, test/add-or-update

#185 Pub 2340 b
  tf-kv-secrets.tf
Labels: stg/add-or-update, prod/add-or-update

#186 Revert "Pub 2340 b"
  tf-kv-secrets.tf
Labels: stg/add-or-update, prod/add-or-update
